# Generated by Django 5.0.6 on 2024-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefeitura', models.CharField(max_length=50)),
                ('coluna_1234', models.CharField(max_length=50)),
            ],
        ),
    ]
